// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsI3rEFYtmrS2Og3UxBXWblK3UTyPs-94',
    appId: '1:57601764622:web:15ab60217bb39d310b3b5f',
    messagingSenderId: '57601764622',
    projectId: 'hall-sync',
    authDomain: 'hall-sync.firebaseapp.com',
    storageBucket: 'hall-sync.appspot.com',
    measurementId: 'G-QP31LW8JHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjX5vkVxjoOjkGy3tcQCU9O0In1rdmtlQ',
    appId: '1:57601764622:android:d6163d9b889e57520b3b5f',
    messagingSenderId: '57601764622',
    projectId: 'hall-sync',
    storageBucket: 'hall-sync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzKp9nwRa1mzjyXYhUOy90DSl1i99IOs4',
    appId: '1:57601764622:ios:e60fe25f37f9b8f10b3b5f',
    messagingSenderId: '57601764622',
    projectId: 'hall-sync',
    storageBucket: 'hall-sync.appspot.com',
    iosBundleId: 'com.hariharanvj.hallSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzKp9nwRa1mzjyXYhUOy90DSl1i99IOs4',
    appId: '1:57601764622:ios:3d48d7c8d2ebd8be0b3b5f',
    messagingSenderId: '57601764622',
    projectId: 'hall-sync',
    storageBucket: 'hall-sync.appspot.com',
    iosBundleId: 'com.hariharanvj.hallSync.RunnerTests',
  );
}
